name: Python Tests

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run linting with Flake8
      run: |
        flake8 --config=pyproject.toml wells

  unittest:

    runs-on: ubuntu-latest

    needs: [lint]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test with pytest
      env:
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        pytest -v -m "not integration"

  integrationtest:
    runs-on: ubuntu-latest

    needs: [lint]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test
      env:
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        pytest -v -m "integration"

  post-test:
    runs-on: ubuntu-latest
    needs: [unittest, integrationtest]

    steps:
      - run: echo "Congratulations! The previous jobs ran successfully!"
